name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
        id-token: write 
        contents: read 
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec jekyll build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::331208789346:role/GithubAction
        aws-region: us-east-1 
    - name: Deploy to S3
      run: |
        aws s3 sync ./_site/ s3://ricksm.it --delete --cache-control max-age=604800
    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
